### ISSUE TITLE
UI Changes and More

### ISSUE THREAD

**Issue by IRONB0SS** [FrostySo/Ps4-Pkg-Sender#23]
Hi FrostySo, Thanks for the app and putting your time on this, I have some suggestions so I hope You look to it

A Setting area would be awesome to control the app

![Screenshot 2023-03-31 145525](https://user-images.githubusercontent.com/97769328/229113838-b9fc048a-4ccc-4fb8-b96b-ff9f9d7e4bd2.png)
.
.
.
Let us Customize the app even more :)
![Screenshot 2023-03-31 143056](https://user-images.githubusercontent.com/97769328/229114201-43a2f0be-88c1-4a4d-b48f-d29a6904db76.png)
Status sentences replaced by icons: 🔁❌✔ and when you hover one ❌ a message pop-up with reason of error

![Screenshot 2023-03-31 153459](https://user-images.githubusercontent.com/97769328/229116232-de1c06b7-f6ce-431d-b3cf-65d6e642c2c8.png)
align column Horizontal/vertical: Center
.
.
**Report Bug**: The app doesn't Work with the latest NodeJS (node-v18.15.0-x64) and works fine with node-v14.15.3-x64

**Comment by FrostySo** [comment]
I can add another column for the icons, but status provides a bigger benefit than just the icons. If some errors happen, the status tells you the error, an image doesn't really portray that. The settings I can add, but won't be able to do it till maybe mid April. If I get free time before that I can try add it before, but not promises. It's on the list. 

Sounds wise, I'm not sure what sounds would be elegant for this matter. If you could suggest some, that would be great. Just make sure the sounds are free to use

As for the NodeJs not working on the later versions, I'll look into that too. I'd only have to assume they changed something. Hopefully it's fixable though.

**Comment by IRONB0SS** [comment]
> I can add another column for the icons, but status provides a bigger benefit than just the icons. If some errors happen, the status tells you the error, an image doesn't really portray that. The settings I can add, but won't be able to do it till maybe mid April. If I get free time before that I can try add it before, but not promises. It's on the list. 
> 
> EDIT: Should not that I'm not sure if C# allows tooltips in images with listview. Though, if it does, I can replace it all with icons sure.
> 
> Sounds wise, I'm not sure what sounds would be elegant for this matter. If you could suggest some, that would be great. Just make sure the sounds are free to use
> 
> As for the NodeJs not working on the later versions, I'll look into that too. I'd only have to assume they changed something. Hopefully it's fixable though. 

Thanks for responding, I will looking for some good sounds and will send 'em to you

**Comment by IRONB0SS** [comment]
> Sounds wise, I'm not sure what sounds would be elegant for this matter. If you could suggest some, that would be great. Just make sure the sounds are free to use

Sounds with .wav format : [MEGA](https://mega.nz/folder/4vgRDTSA#dmR-3YNd4OrU8GlFVsQ3mA)

**Comment by FrostySo** [comment]
> **Report bug** Delete function doesn't work at all, for example I added FIFA with update and then deleted the update from app but it installed afterward

I see it, will be fixed soon. A complete oversight, deleted it from the UI but forgot to remove it from the actual queue...

**Comment by FrostySo** [comment]
Hey man I know it's been a while. Just reminding you that I haven't forgotten about this. 

Just been extremely busy lately and hopefully I can take a look eventually. The UI deletion is fixed on the git but I haven't made a build for it. You can either compile it yourself or just wait a bit longer.

**Comment by IRONB0SS** [comment]
> You can either compile it yourself or just wait a bit longer.

Hey friend, thanks for the efforts, I have zero knowledge about programming so I can wait :)

**Comment by IRONB0SS** [comment]
@FrostySo
Hey again, is it possible to add a option for this?
"Force update file to send"
What do I mean is when a game has update for example Minecraft is installed with update v1.64 and If I try to send Update 1.66, the Sender says update is installed, Is there a way to bypass this?

**Comment by FrostySo** [comment]
> @FrostySo Hey again, is it possible to add a option for this? "Force update file to send" What do I mean is when a game has update for example Minecraft is installed with update v1.64 and If I try to send Update 1.66, the Sender says update is installed, Is there a way to bypass this? ![IMG_20230609_111833_060.jpg](https://user-images.githubusercontent.com/97769328/244628008-cbdf1125-23cb-494e-8c0e-016ffb4d64fe.jpg)

I'll see what I can do. I think it is a limitation with the package sender itself, it doesn't let me see what updates are already installed. If at all possible, I can add a "force uninstall update" option which will force uninstall an update if you're trying to send one. However, I do believe I cannot distinguish the difference between DLC and update, so it might uninstall DLC too. I will also add it to my list of things to look into.

**Comment by IRONB0SS** [comment]
@FrostySo 
I remember that I could send update PKG to PS4 with modded warfare RPI but after windows 10 updates, his tool didn't work anymore

**Comment by FrostySo** [comment]
> @FrostySo I remember that I could send update PKG to PS4 with modded warfare PKG Sender but after windows 10 updates, his tool didn't work anymore

Yea because his tool didn't have any checks to see if it was installed or not. The reason why it says already installed is because I check to see if the file has already been sent. I don't really remember why I went with this approach but I'm sure it was for a good reason. I can probably add a skip check option by minimum though. 

Once I work on this again I will see what I can do.

**Comment by IRONB0SS** [comment]
> I don't really remember why I went with this approach but I'm sure it was for a good reason. I can probably add a skip check option by minimum though. 

of course it's good feature, Skip check option is what is needed for some situations
Also Checking feature is really necessary and must be turned on by default just like now

Thanks for the efforts and your time, I cannot wait to try new version 🙌❤️

**Comment by FrostySo** [comment]
Okay so I know why I did it like that. for RPI, uninstalling a patch and knowing whether a specific patch is installed is impossible to know. It uses the Title ID to install/uninstall patches which is an issue when it comes to installing/uninstalling. Why? Because we cannot tell what specific patch was installed. There is no endpoint for checking to see if a specific patch is installed, or to get a list of current patches installed. The package installer should automatically install the newer version by default (assuming he handles it on his end). So therefore, we'd need to force uninstall all patches before installing new patches, if you want to be safe. But this behavior can cause undefined problems, as some patches require a higher version to install that patch, and it's not possible to know which patch needs that and which doesn't.

For that reason specifically, I cannot really do much to make it be accurate. I can make it skip the install check itself, but I'm unsure if that will help (it might). Since it's all generalized and not specific. Had he used content ID instead, it would have been a fool proof method which would let us easily know if that specific patch was installed or not. But yea, I'll add that option anyways and hopefully it makes a difference. But if it doesn't, then I apologize I cannot really do much about it. There just isn't enough data I can get out of RPI. Had it only used content id this could've been easily resolved :'(

**Comment by IRONB0SS** [comment]
@FrostySo
Thanks for explanation, check skipping should do the job and no need to apologize if it didn't work, you're doing a favor here, thanks for the efforts

Is there ETA for the release?

**Comment by FrostySo** [comment]
> Is there ETA for the release?

Well theming itself will take some time, especially on my schedule. But if you wane me to add that option probably can get it done by end of the week.

**Comment by IRONB0SS** [comment]
> if you wane me to add that option probably can get it done by end of the week.

Weekend is fine also I can test it, thanks in advance

**Comment by FrostySo** [comment]
> > if you wane me to add that option probably can get it done by end of the week.
> 
> Weekend is fine also I can test it, thanks in advance

Hi, try this. Hopefully it resolves what you're looking for otherwise I will probably just revert it back. 

There's also a couple of changes

Including deleting items from queue, reworked some things to hopefully make it work with all node js versions and a few minor improvements. Things like that. 

[Ps4-Pkg-Sender - Skip Install Check option.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/12117124/Ps4-Pkg-Sender.-.Skip.Install.Check.option.zip)

Sadly the UI side of things, may take a while. It's not easy to make things very modular for the end user and I am pretty busy myself so, maybe one day it will eventually get finished.

**Comment by IRONB0SS** [comment]
Thanks a lot, Skip Install Check works flawlessly but app needs restart after enabling/disabling

Aslo Delete function do the job, thank you!


New UI Bug : Status is not displayed now 

![IMG_20230722_211326_013.jpg](https://github.com/FrostySo/Ps4-Pkg-Sender/assets/97769328/cd20e456-d8fd-4dc3-95bb-9030261ebdc9)

**Comment by FrostySo** [comment]
> Thanks a lot ❤️, Skip Install Check works flawlessly but app needs restart after enabling/disabling to apply changes

 Oops my bad Oversight. I will fix this. 

> Aslo Delete function do the job, THANK YOU AGAIN !

Np 

> New UI Bug: Status is not displayed now

Yea I noticed this too, I'm not sure how to fix it. For me it happened once, then never happened again after that. It's completely random to me. Can you try again but with a game? Might be specific to other things. Were you focused on the RPI on the ps4 when it happened? Or did it say "All done" even though it wasn't even finished/just started? Also What nodejs version are you on as well? 

 
> **Request**: • please change app font to Segoe UI Regular or Open Sans with customizable Size [Small/Medium/Large]

 Yea, that's what the theming was going to allow. I'm kind of hesitant to change the font and stuff in general, but if I can get theming out sooner or later this will be possible to do on your end.

> • Change type description of Additional_Connect to DLC or Addon 😄 ![Screenshot 2023-07-22 214342](https://user-images.githubusercontent.com/97769328/255345317-a1038254-1c43-4e0f-9bd4-54e54c78086b.png)

Additional content is actually what is shown on the ps4. If it doesn't impact the sender in any way I will change it to DLC. Because I think additional content doesn't only show DLC's but other things too, such as themes and stuff. I'll look into this though, and see what's more appropriate.

**Comment by IRONB0SS** [comment]
New Bug :
Games stuck at certain point but it's random per games
with 1.07 beta
![Screenshot 2023-07-24 194847](https://github.com/FrostySo/Ps4-Pkg-Sender/assets/97769328/7d886126-d3e8-4861-b240-b136b3216685)

with 1.07 final
![Screenshot 2023-07-24 201921](https://github.com/FrostySo/Ps4-Pkg-Sender/assets/97769328/e86e1ad8-4ca7-4447-b3ee-1a0afb4819b4)

Node Js Version : 14.15.3

**Comment by FrostySo** [comment]
> Node Js Version : 14.15.3 Anti Virus /Firewall turned off GoldHEN 2.4b14 FW : 09.00
> 
> Edit : Tried with lastest NodeJS v18.17.0 with npm updated and still stuck at 13%, I will test with more PS4s and will keep you posted


Next time this happens, can you check to see in your task manager if nodejs is running? I'm not certain why it crashes randomly, but it should have started back up automatically. Might need a better way of opening nodejs up.

**Comment by IRONB0SS** [comment]
> Next time this happens, can you check to see in your task manager if nodejs is running?
![image](https://github.com/FrostySo/Ps4-Pkg-Sender/assets/97769328/6d4419f5-1f23-4b10-9102-12c3996d55fc)

**Comment by FrostySo** [comment]
Ah yea I forgot to mention that it has many processes. Node.js javascript runtime is always running in the background and I'm not certain the other one. Next time can you use the "Details" view. I think you will be looking for "node.exe". But my guess is that it crashed if it's like that and not sending on your end. 

I might try a custom HTTP server outside of node and see if that works better. Otherwise I'd be reverting back to the old method.

**Comment by IRONB0SS** [comment]
the highlighted one uses memory and CPU

![image](https://github.com/FrostySo/Ps4-Pkg-Sender/assets/97769328/9e933497-4fe2-43e9-bec1-6291c2e8ded2)

**Comment by FrostySo** [comment]
Weird how it's still happening even when nodejs is running. If nodejs is running and it bugs out then It's on the pkg sender or maybe the HEN version you're using. I'll look into it later and will try with my own http server solution/an already existing solution first to see if it still happens. 

Right now, I am almost done with customization, hopefully this week. You'll be able to customize everything down to the brim so you can have it the way you like it (colors, fonts, hover color etc).

**Comment by IRONB0SS** [comment]
> maybe the HEN version you're using.

I will try with Older GoldHEN Soon, but there is no problem with 1.07 final

> Right now, I am almost done with customization, hopefully this week. You'll be able to customize everything down to the brim so you can have it the way you like it (colors, fonts, hover color etc).

that's awesome, thanks a million ❤

**Comment by FrostySo** [comment]
Ended up reverting the changes and the problem still occurred. So I un-re-reverted the changes. Thankfully a restart of the nodejs server seems fix it, so I will just make it monitor the progress. If it's stuck on an abnormal total time for too long, I'll make it auto restart the http server. I'm not sure why it doesn't happen in the older version but does in the newer version, I checked the commits I made and what I did shouldn't have changed anything. 

Because even the NODEJS server itself threw 0 errors when this happened. It was behaving normally.

Outside of this, hoping to be done soon. Then you can test it. Just know that when it gets stuck next time, give it some time to monitor and restart the server before telling me it's stuck.

**Comment by FrostySo** [comment]
[Ps4-Pkg-SenderV1.08.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/12269014/Ps4-Pkg-SenderV1.08.zip)

Let me know how it is. The columns thing I haven't added yet, that looks fairly easy but because I use WinForms it's not as easy to achieve. Eventually I will add it in though, sorry if you were excited for that. Theming though, is available. Eventually I'll add the context menu in to be themable, but right now I will just leave it as is. 

I'm more worried about the functionality of the program. I have re-written the code 1 more time for handling the server. I tried my best to get it to screw up on me but It didn't. So does that mean it's perfect now? I'm not sure. Just be aware that, for whatever reason the pkg installer crashes after a set amount of requests when polling for the progress. So if you have a very big list it might crash regardless. But I'm pretty sure when RPI crashes it crashes on your PS4, so you'd know. 

Just let me know how it goes.

**Comment by IRONB0SS** [comment]
Thanks a lot for the efforts friend, I'll use this version and I let you know how it works after a while, you did too much, thanks again ❤

**Comment by FrostySo** [comment]
sure thing

**Comment by IRONB0SS** [comment]
Hey Again, I think you can release the v1.08, So far so good

![Screenshot 2023-08-27 001936](https://github.com/FrostySo/Ps4-Pkg-Sender/assets/97769328/622f70e0-c9fe-4129-aaa3-34b64f4e6cd6)

also still we should Restart the app after enabling/disabling "install Check" so if you have no time to fix it, simply tell users to restart the app

**Comment by FrostySo** [comment]
Okay there's 1 more thing left and that's the context menu. That's great that it all works fine! 

Why should we restart the app for install check? I thought I fixed it and made it persist, but if I didn't I will fix it.

**Comment by FrostySo** [comment]
@IRONB0SS 

[Ps4-Pkg-SenderV1.08.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/12568032/Ps4-Pkg-SenderV1.08.zip)

Give this a go. Should be all done! Just as a precaution backup "themesettings.json" incase the newly added themable context menu breaks it somehow.

**Comment by IRONB0SS** [comment]
Thanks a lot, I'll keep you posted after testing the app, much appreciated

**Comment by IRONB0SS** [comment]
@FrostySo 
so far so good, skip install has been fixed now
didn't notice any bug/error yet

but I have request if its possible, is it possible when we define custom color it remain till app close? I literally defined custom color to each section and I know its just one time but I thought it worth to ask you, that can save time a little bit :)

Thank You for putting time on this ❤

**Comment by IRONB0SS** [comment]
Hey @FrostySo,
I tested the app for about a month and you can release it, everything works flawlessly 👍

Thanks a million for putting your time and listening to feedbacks, Please put donation button at Final release

good luck my friend ❤️, I'm going to close this issue, nothing left to do ;)

**Comment by FrostySo** [comment]
> Hey @FrostySo, I tested the app for about a month and you can release it, everything works flawlessly 👍
> 
> Thanks a million for putting your time and listening to feedbacks, Please put donation button at Final release
> 
> good luck my friend ❤️, I'm going to close this issue, nothing left to do ;)

Glad you enjoy the software. 

I'll release it when I have time sure

It's fine man you can keep your money, I appreciate the gesture but you are better off using it for yourself. I don't need it. This was just a fun project for me and when the ps5 remote package installer comes out, I will make the appropriate changes to make it work with that as well. However, I'd be unable to test that due to not owning a JB'able PS5. But there's a chance that the ps4 version may work for the ps5 once all is refined.

**Comment by IRONB0SS** [comment]
>It's fine man you can keep your money, I appreciate the gesture but you are better off using it for yourself. I don't need it. This was just a fun project for me.

This is pure kindness, THANK YOU SIR, I hope you and your family stay healthy and happy

Best regards ❤️

**Comment by IRONB0SS** [comment]
Hey @FrostySo, how are you?

Could you turn this website into offline windows app?

https://hardwaretester.com/gamepad

the gamepad tester section would be enough, also with dark mode and let users choose controller between Xbox and PS

I don't have much knowledge about coding but they added this message to their website : "Are you a developer interested in using the Gamepad API? Check out this [quick guide.](https://hardwaretester.com/gamepad/for-developers)"

thanks in advance ❤🙏🏻

**Comment by FrostySo** [comment]
> Hey @FrostySo, how are you?
> 
> Could you turn this website into offline windows app?
> 
> https://hardwaretester.com/gamepad
> 
> the gamepad tester section would be enough, also with dark mode and let users choose controller between Xbox and PS
> 
> I don't have much knowledge about coding but they added this message to their website : "Are you a developer interested in using the Gamepad API? Check out this [quick guide.](https://hardwaretester.com/gamepad/for-developers)"
> 
> thanks in advance ❤🙏🏻

Sorry man I'm not really a web dev. I mean it's not that hard to do, just time consuming. You'd have to just download all the files and locally point them to the necessary dependencies. However, it ultimately depends on how the site was built. But if it's built normally, you can indeed put this into an electron app. Maybe send him an email and let him know? But I'm pretty sure he doesn't provide and offline version because of the ads

**Comment by IRONB0SS** [comment]
Hey Bro, How Are You? I'm hope You're Okay

Do You have time for another FUN Project? :)

Could You turn this app into this?

![Untitled-1](https://github.com/FrostySo/Ps4-Pkg-Sender/assets/97769328/94275b6e-687b-4217-8af2-a3d761b771e4)

I was inspired by your app UI

The original App Source Code : github.com/KOPElan/PSX-Download-Helper

The Updated one by another dude : github.com/rasoulia/PSXDownloader (better at managing Logs)

This app used to for sending Retail PKG to PS4 and PS5

You can Call this App PSN Data Sender

If you say Yes I'll send more information about this app

**Comment by IRONB0SS** [comment]
Hey Buddy, What's up? I hope You and your family is okay and healthy

I'm here to report a bug and I'm hoping you could fix it

When I add a few games, the app crashes only on patches and I need to re-import them
 
![image](https://github.com/FrostySo/Ps4-Pkg-Sender/assets/97769328/abb7e57e-4cfd-4341-b982-3690fdab8d18)

is this from the app or from the RPI?


Also this UI bug can be fixed?
![Recording2024-03-27014622-ezgif com-video-to-gif-converter](https://github.com/FrostySo/Ps4-Pkg-Sender/assets/97769328/0ee5b3f8-294f-47f0-9bd5-7e68761ea6f4)

**Comment by FrostySo** [comment]
The first issue is an issue with RPI in itself, when calling the getProgress function from RPI it returns back the amount of bytes received and how many are remaining. For whatever reason, this causes RPI to crash if called enough times. That's why I added check delay, to reduce the amount of times it would be called and therefore, in theory, help you install more before it crashes. It is out of my hands unfortunately. You could try make the check delay every 60-120s and see if it'll help.

Also I think you can just re-queue it? I don't think you need to reimport it all. 


Second "bug" is just because I make it autofill the text to the screen based on the text's length and it doesnt take window size into account. I don't think I'll be fixing it, though I do understand it is frustrating. It's just because this is a tool that gets a job done, it isn't like it's used 24/7 as an actual program. So I just don't think it's worthwhile fixing it, since it doesnt harm functionality.

**Comment by IRONB0SS** [comment]
Hey buddy thanks for the answer and I didn't know you fix re-queue it's easy from exporting/importing

Have a nice day

**Comment by IRONB0SS** [comment]
Hello Friend, How are You?
there are some DLC files that cannot be transfer with the app, I assume this happens only if DLC is "Volume Type: Additional Content Package without Extra Data"

![Image](https://github.com/user-attachments/assets/6d987417-a99a-48c5-95e9-7f624fbc94a3)

[Games DLC.zip](https://github.com/user-attachments/files/19163013/Games.DLC.zip)

Could you implement a checkbox to skip this Volume type? Thanks in advance

also my friend [Created a PKG sender for retail PKGs](https://github.com/IRONB0SS/PSXhub), Could we use your app icon with different colors?

**Comment by IRONB0SS** [comment]
Hey Again, I have no idea why but whenever the app trying to send addons, RPI Crashes

![Image](https://github.com/user-attachments/assets/0e1cf86e-fc88-417f-8da5-107dbba30de8)
